export default {
    error: "/Error",
    notFound: "/Not-Found",
    predictions: "/Predictions",
    matches: "/Matches",
    login: "/Login",
    selectPool: "/Select-Pool",
    standings: "/Standings",
    rules: "/Rules",
    userPredictions: "/User-Predictions/:poolParticipantId",
    deadlines: "/Deadlines",
    bracket: "/Bracket",
    bracketDeadlines: "/Bracket-Deadlines",
    myGuesses: "/My-Guesses",
    settings: "/Settings",
}